version: '3.7'
services:
    opencart:
        image: ameseguer/opencart
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_ROOT_PASSWORD: "rootpwd"
        networks:
        - student
        deploy:
          mode: replicated
          replicas: 1
          update_config:
            parallelism: 1
            delay: 10s
          restart_policy:
            condition: on-failure
          labels:
            - "traefik.enable=true"
            - "traefik.docker.network=student"
            #HTTP
            - "traefik.http.services.ion-exam-${PREFIX}.loadbalancer.server.port=80"
            - "traefik.http.routers.ion-exam-${PREFIX}.entrypoints=web"
            - "traefik.http.routers.ion-exam-${PREFIX}.rule=Host(`user${PREFIX}.akaorigin.com`)||Host(`user${PREFIX}exam.my-akashop.com`)"
            #HTTPS
            - "traefik.http.routers.ion-exam-${PREFIX}-websecure.entrypoints=websecure"
            - "traefik.http.routers.ion-exam-${PREFIX}-websecure.tls=true"
            - "traefik.http.routers.ion-exam-${PREFIX}-websecure.tls.certresolver=letsencrypt"
            - "traefik.http.routers.ion-exam-${PREFIX}-websecure.rule=Host(`user${PREFIX}.akaorigin.com`)||Host(`user${PREFIX}exam.my-akashop.com`)"           
    juiceshop:
        image: bkimminich/juice-shop:v11.1.3
        networks:
        - student
        deploy:
          mode: replicated
          replicas: 1
          update_config:
            parallelism: 1
            delay: 10s
          restart_policy:
            condition: on-failure
          labels:
            - "traefik.enable=true"
            - "traefik.docker.network=student"
            #HTTP
            - "traefik.http.services.ion-${PREFIX}.loadbalancer.server.port=3000"
            - "traefik.http.routers.ion-${PREFIX}.entrypoints=web"
            - "traefik.http.routers.ion-${PREFIX}.rule=Host(`user${PREFIX}exam.akaorigin.com`)||Host(`user${PREFIX}exam.my-akashop.com`)"
            #HTTPS
            - "traefik.http.routers.ion-${PREFIX}-websecure.entrypoints=websecure"
            - "traefik.http.routers.ion-${PREFIX}-websecure.tls=true"
            - "traefik.http.routers.ion-${PREFIX}-websecure.tls.certresolver=letsencrypt"
            - "traefik.http.routers.ion-${PREFIX}-websecure.rule=Host(`user${PREFIX}exam.akaorigin.com`)||Host(`user${PREFIX}exam.my-akashop.com`)"
networks:
  student:
    external: true
